### ISSUE TITLE
这种带注解的读取 一旦带偏移 量 就报错，  读取list的正常 

### ISSUE THREAD

**Issue by OliverVin** [Crab2died/Excel4J#16]
ExcelUtils.getInstance().readExcel2Objects(EXCEL_FILE_PATH, PKQuestion.class, 2, 10 0);

这种带注解的读取 一旦带偏移 量 就报错，  读取list的正常 ！ 如果2 变成0， 从0读取就正常

报错信息如下：
java.lang.IllegalStateException: Cannot get a STRING value from a NUMERIC cell
	at org.apache.poi.xssf.usermodel.XSSFCell.typeMismatch(XSSFCell.java:1077)
	at org.apache.poi.xssf.usermodel.XSSFCell.getRichStringCellValue(XSSFCell.java:395)
	at org.apache.poi.xssf.usermodel.XSSFCell.getStringCellValue(XSSFCell.java:347)
	at com.github.crab2died.utils.Utils.getHeaderMap(Utils.java:113)
	at com.github.crab2died.ExcelUtils.readExcel2ObjectsHandler(ExcelUtils.java:251)
	at com.github.crab2died.ExcelUtils.readExcel2Objects(ExcelUtils.java:127)
	at com.github.crab2died.ExcelUtils.readExcel2Objects(ExcelUtils.java:171)
	at cn.ifuli.ciq.data.works.api.export.pk.ExportPkImpl.handleExcel(ExportPkImpl.java:109)
	at cn.ifuli.ciq.data.works.api.export.pk.ExportPkImpl.executeImportAction(ExportPkImpl.java:77)
	at cn.ifuli.ciq.data.works.api.export.pk.ExportPkImpl.execute(ExportPkImpl.java:64)
	at cn.ifuli.ciq.data.works.App.dispatch(App.java:102)
	at cn.ifuli.ciq.data.works.App$1.onMsg(App.java:46)
	at cn.ifuli.ciq.data.works.Consumer$1.handleDelivery(Consumer.java:76)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by OliverVin** [comment]
有人吗 给个回复啊
