### ISSUE TITLE
导入问题，method为null

### ISSUE THREAD

**Issue by charlieDJ** [Crab2died/Excel4J#35]
前提：项目引用lombok，在导入的实体类上面添加@getter，@setter注解。
导入Excel时复制属性，不能获取method对象，抛出NullPointException。

**Comment by PengTan-Capillarytech** [comment]
请问您解决了吗   我即使手写get  set也不行   抛出Caused by: com.github.crab2died.exceptions.Excel4JException: java.beans.IntrospectionException: Can not get the getter or setter method
	at com.github.crab2died.utils.Utils.copyProperty(Utils.java:327)
	at com.github.crab2died.ExcelUtils.readCSVByMapHandler(ExcelUtils.java:1574)
	at com.github.crab2died.ExcelUtils.readCSV2Objects(ExcelUtils.java:1515)
	... 2 more
Caused by: java.beans.IntrospectionException: Can not get the getter or setter method
	at com.github.crab2died.utils.Utils.getterOrSetter(Utils.java:248)
	at com.github.crab2died.utils.Utils.copyProperty(Utils.java:319)
	... 4 more

**Comment by liangxp** [comment]
我也不行，我去
